version: "1.0"
info:
  model: int-scaffold
packages:
- name: NL_MIHE_GitbasedProject
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo/NL_MIHE_GitbasedProject
  gitUsername: elpinjo
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
- name: OrderAnalytics
  version: "1.0"
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo
  gitUsername: elpinjo
  gitBranch: master
- name: OrderEntry
  version: "2.0"
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo
  gitUsername: elpinjo
  gitBranch: master
services:
- serviceName: project.nl_mihe_gitbased.integrations:InsertOrder
  packages:
  - name: NL_MIHE_GitbasedProject
    version: "1.0"
  - name: OrderEntry
    version: 2.0.3
  - name: WmStreaming
    version: 12.0.0.0.1
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
  - name: OrderAnalytics
    version: 1.0.2
- serviceName: orderentry.service:insertOrder
  packages:
  - name: OrderEntry
    version: 2.0.3
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
- serviceName: orderentry.adapter:createOrder
  packages:
  - name: OrderEntry
    version: 2.0.3
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
- serviceName: orderentry.adapter:insertLineItems
  packages:
  - name: OrderEntry
    version: 2.0.3
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
- serviceName: order.analytics.flows:publishNewOrderEvent
  packages:
  - name: OrderAnalytics
    version: 1.0.2
  - name: WmStreaming
    version: 12.0.0.0.1
- serviceName: pub.math:multiplyFloats
  packages:
  - name: WmPublic
    version: 11.1.0.0.2015
- serviceName: pub.math:addFloats
  packages:
  - name: WmPublic
    version: 11.1.0.0.2015
- serviceName: pub.streaming:send
  packages:
  - name: WmStreaming
    version: 12.0.0.0.1
configurationVariables:
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.serverName
  : localhost
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.portNumber
  : "3306"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.dbType
  : MySQL
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.poolable
  : "false"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.networkProtocol
  : ""
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.trustStore
  : ""
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.password
  : "{AES}aYrXC43dTWsDUHRWG5mhTA=="
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.databaseName
  : ordermgt
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.driverType
  : mysqlDriverGroup
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.user
  : root
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.keyStore
  : ""
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.NL_MIHE_GitbasedProject.project.nl_mihe_gitbased.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.OrderDatabase.connectionEnabled
  : "false"
